#! /bin/bash

#.  ~/.config/colors/yandere.sh

[options]
resize_grip = false
scroll_on_output = false
scroll_on_keystroke = true
audible_bell = false
visible_bell = false
mouse_autohide = true
allow_bold = true
dynamic_title = true
urgent_on_bell = true
clickable_url = true
font = Roboto Mono for Powerline 9
scrollback_lines = 1000
search_wrap = true

cursor_blink = system
cursor_shape = underline
browser = firefox

size_hints = true

[colors]

# special
foreground      = #fef0ff
foreground_bold = #fef0ff
cursor          = #fef0ff
background      = #0e0c19

# black
color0  = #0e0c19
color8  = #0e0c19

# red
color1  = #f85888
color9  = #f85888

# green
color2  = #8785c7
color10 = #8785c7

# yellow
color3  = #ff8498
color11 = #ff8498

# blue
color4  = #fea2a3
color12 = #fea2a3

# magenta
color5  = #ffffe3
color13 = #ffffe3

# cyan
color6  = #fedafe
color14 = #ff96c7

# white
color7  = #ff96c7
color15 = #fedafe

