#! /bin/sh

bspc monitor -d i ii iii iv v vi vii viii ix x

bspc config border_width          2
bspc config window_gap           45
bspc config top_padding          75
bspc config bottom_padding        0
bspc config right_padding         0
bspc config left_padding          0

bspc config focused_border_color  "#ef589c"
bspc config active_border_color   "#ef589c"
bspc config normal_border_color   "#3c3955"

bspc config split_ratio           0.55
bspc config borderless_monocle    true
bspc config gapless_monocle       true

#mouse acitons
bspc config pointer_modifier    mod4
bspc config pointer_action1     move
bspc config pointer_action2   resize
bspc config click_to_focus      true