#!/bin/sh
#
#~/.xinitrc
#

xrdb -merge ~/.Xresources
xbindkeys &

sxhkd -c ~/.config/sxhkd/sxhkdrc &
termite --exec='bspc monitor eDP-1 -d i ii iii iv v' &
compton --config ~/.config/compton/compton.conf &
feh --bg-fill ~/configs/Wallpapers/Twilight.png
polybar -c ~/configs/Twilight/polybar/config yuki &

exec bspwm -c ~/configs/Twilight/bspwm/bspwmrc